#!/bin/bash

cd /tmp

export GOENV_VERSION=1.7.0
export GOENV_LATEST_VERSION=$(curl --silent "https://api.github.com/repos/Spacewalkio/Goenv/releases/latest" | jq '.tag_name' | sed -E 's/.*"([^"]+)".*/\1/')
echo "Installing Goenv $GOENV_VERSION. Latest version is $GOENV_LATEST_VERSION"

curl -sL https://github.com/Spacewalkio/Goenv/releases/download/v{$GOENV_VERSION}/goenv_{$GOENV_VERSION}_Darwin_x86_64.tar.gz | tar xz

chmod +x ./goenv

mv -f goenv $LOCAL_BIN/goenv
