echo "GIT_AUTHOR_NAME=\"$GIT_AUTHOR_NAME\"
GIT_COMMITTER_NAME=\"$GIT_AUTHOR_NAME\"
GIT_AUTHOR_EMAIL=\"$GIT_AUTHOR_EMAIL\"
GIT_COMMITTER_EMAIL=\"$GIT_AUTHOR_EMAIL\"

PERSONAL_SPACE_GIT_AUTHOR_NAME=\"$PERSONAL_SPACE_GIT_AUTHOR_NAME\"
PERSONAL_SPACE_GIT_AUTHOR_EMAIL=\"$PERSONAL_SPACE_GIT_AUTHOR_EMAIL\"
WORK_SPACE_GIT_AUTHOR_NAME=\"$WORK_SPACE_GIT_AUTHOR_NAME\"
WORK_SPACE_GIT_AUTHOR_EMAIL=\"$WORK_SPACE_GIT_AUTHOR_EMAIL\"
" > ~/.extra

echo "
[user]
    name = \"$PERSONAL_SPACE_GIT_AUTHOR_NAME\"
    email = \"$PERSONAL_SPACE_GIT_AUTHOR_EMAIL\"
" >> ~/.gitconfig-personal-space

echo "
[user]
    name = \"$WORK_SPACE_GIT_AUTHOR_NAME\"
    email = \"$WORK_SPACE_GIT_AUTHOR_EMAIL\"
" >> ~/.gitconfig-work-space
