version: '3.8'

services:
    # Prometheus Container
    prometheus:
        image: prom/prometheus:v2.55.1
        command:
            - --config.file=/etc/prometheus/prometheus.yml
            - --web.enable-remote-write-receiver
            - --enable-feature=exemplar-storage
            - --storage.tsdb.path=/prometheus
            - --web.external-url=/prometheus/
            - --web.route-prefix=/
            - --log.level=info
            - --log.format=json
        volumes:
            - ./configs/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
            - prometheus_data:/prometheus
        ports:
            - 9090
        restart: unless-stopped

    # Grafana Container
    grafana:
        image: grafana/grafana:11.3.0
        environment:
            - GF_SECURITY_ADMIN_USER=${ADMIN_USER:-admin}
            - GF_SECURITY_ADMIN_PASSWORD=${ADMIN_PASSWORD:-admin}
            - GF_USERS_ALLOW_SIGN_UP=false
            - GF_FEATURE_TOGGLES_ENABLE=publicDashboards
        volumes:
          - ./configs/grafana/grafana.ini:/etc/grafana/grafana.ini
          - grafana_data:/var/lib/grafana
          - grafana_logs:/var/log/grafana
        ports:
            - 3000
        restart: unless-stopped

    # Loki Container
    loki:
        image: grafana/loki:3.4.2
        command:
            - -config.file=/etc/loki/local-config.yaml
        ports:
            - 3100
        restart: unless-stopped

    # Alertmanager Container
    alertmanager:
        image: prom/alertmanager:v0.28.0
        command:
            - --config.file=/etc/alertmanager/alertmanager.yml
            - --log.level=info
            - --log.format=json
        ports:
            - 9093
        volumes:
            - ./configs/alertmanager/alertmanager.yml:/etc/alertmanager/alertmanager.yml"
            - alertmanager_data:/data
        restart: unless-stopped

    # Nginx Container
    nginx:
        image: nginx:1.25.4-alpine3.18
        ports:
            - '80:80'
        volumes:
            - ./configs/nginx/nginx.conf:/etc/nginx/nginx.conf
        restart: unless-stopped

volumes:
  prometheus_data:
    driver: local

  grafana_data:
    driver: local

  grafana_logs:
    driver: local

  alertmanager_data:
    driver: local
