# MIT License
#
# Copyright (c) 2010 Clivern
#
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in all
# copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
# SOFTWARE.


tasks:
  - name: Install required packages
    apt:
      name: "{{ item }}"
      state: present
    with_items:
      - wget
      - unzip
      - curl
    when: ansible_os_family == "Debian"

  - name: Download Terraform
    get_url:
      url: https://releases.hashicorp.com/terraform/1.13.1/terraform_1.13.1_linux_amd64.zip
      dest: /tmp/terraform.zip
      mode: '0644'
    when: ansible_os_family == "Debian"

  - name: Extract Terraform
    unarchive:
      src: /tmp/terraform.zip
      dest: /tmp
      remote_src: yes
    when: ansible_os_family == "Debian"

  - name: Copy Terraform to bin directory
    copy:
      src: /tmp/terraform
      dest: /usr/local/bin/terraform
      mode: a+x
      force: true
    when: ansible_os_family == "Debian"

  - name: Clean up temporary files
    file:
      path: "{{ item }}"
      state: absent
    with_items:
      - /tmp/terraform.zip
      - /tmp/terraform
    when: ansible_os_family == "Debian"

  - name: Get Terraform version
    command: terraform version
    register: output
    environment:
      PATH: "/usr/local/bin:{{ ansible_env.PATH }}"
    when: ansible_os_family == "Debian"

  - debug: msg="{{ output.stdout }}"
    when: ansible_os_family == "Debian"
