#!/bin/bash

cd /tmp

export K6_VERSION=v0.42.0
wget https://github.com/grafana/k6/releases/download/$K6_VERSION/k6-$K6_VERSION-macos-amd64.zip
unzip k6-$K6_VERSION-macos-amd64.zip

chmod +x ./k6-$K6_VERSION-macos-amd64/k6

mv -f ./k6-$K6_VERSION-macos-amd64/k6 $LOCAL_BIN/k6

rm -rf k6-$K6_VERSION-macos-amd64
rm -rf k6-$K6_VERSION-macos-amd64.zip
