# MIT License
#
# Copyright (c) 2010 Clivern
#
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in all
# copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
# SOFTWARE.


tasks:
  - name: ensures ~/.config dir exists
    file:
      path: "~/.config"
      state: directory

  - name: installing ripgrep package
    apt:
      name: ripgrep
      state: present

  - name: download neovim to /tmp
    get_url:
      url: "https://github.com/neovim/neovim/releases/download/v0.11.4/nvim-linux-x86_64.tar.gz"
      dest: "/tmp/nvim-linux-x86_64.tar.gz"
      mode: "0644"

  - name: extract neovim archive
    unarchive:
      src: "/tmp/nvim-linux-x86_64.tar.gz"
      dest: "/tmp"
      remote_src: yes

  - name: move neovim to /opt
    copy:
      src: "/tmp/nvim-linux-x86_64/"
      dest: "/opt/nvim"
      mode: "0755"
      remote_src: yes
      force: true

  - name: create symlink for neovim binary
    file:
      src: "/opt/nvim/bin/nvim"
      dest: "/usr/local/bin/nvim"
      state: link

  - name: get version
    command: nvim --version
    register: output

  - debug: msg="{{ output.stdout }}"

  - name: clean up temporary files
    file:
      path: "{{ item }}"
      state: absent
    with_items:
      - "/tmp/nvim-linux-x86_64.tar.gz"
      - "/tmp/nvim-linux-x86_64"

  - name: clean up old neovim configs
    file:
      path: "{{ item }}"
      state: absent
    with_items:
      - "~/.local/share/nvim"
      - "~/.local/state/nvim"
      - "~/.cache/nvim"

  # To delete old configs $ rm -rf ~/.local/share/nvim ~/.local/state/nvim ~/.cache/nvim
  - name: symlink the configs
    file:
      src: "/home/clivern/space/anubis/nvim"
      dest: "~/.config/nvim"
      state: link

  - name: install pylsp with pipx
    command: pipx install python-lsp-server[all]
