# MIT License
#
# Copyright (c) 2010 Clivern
#
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in all
# copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
# SOFTWARE.

secrets:
  # $ op secret add work_email x@rf.com -t work -f
  work_email: work_email

vars:
  personal_name: Clivern
  personal_email: hello@clivern.com
  work_name: Ahmed

templates:
  aliases.j2: aliases.j2
  editorconfig.j2: editorconfig.j2
  exports.j2: exports.j2
  functions.j2: functions.j2
  gitattributes.j2: gitattributes.j2
  gitconfig-personal.j2: gitconfig-personal.j2
  gitconfig-work.j2: gitconfig-work.j2
  gitconfig.j2: gitconfig.j2
  gitignore.j2: gitignore.j2
  anubis.j2: anubis.j2

tasks:
  - name: create root config files
    template:
      src: "{{ item.src }}"
      dest: "{{ item.dest }}"
      mode: "{{ item.mode }}"
    with_items:
      - { src: "editorconfig.j2", dest: "~/.editorconfig", mode: "0600" }
      - { src: "gitattributes.j2", dest: "~/.gitattributes", mode: "0600" }
      - { src: "gitconfig-personal.j2", dest: "~/.gitconfig-personal", mode: "0600" }
      - { src: "gitconfig-work.j2", dest: "~/.gitconfig-work", mode: "0600" }
      - { src: "gitconfig.j2", dest: "~/.gitconfig", mode: "0600" }
      - { src: "gitignore.j2", dest: "~/.gitignore", mode: "0600" }
      - { src: "aliases.j2", dest: "~/.aliases", mode: "0600" }
      - { src: "exports.j2", dest: "~/.exports", mode: "0600" }
      - { src: "functions.j2", dest: "~/.functions", mode: "0600" }
      - { src: "anubis.j2", dest: "/usr/local/bin/anubis", mode: "a+x" }

  - name: create clivern config files
    template:
      src: "{{ item.src }}"
      dest: "{{ item.dest }}"
      mode: "{{ item.mode }}"
      owner: "clivern"
      group: "clivern"
    with_items:
      - { src: "aliases.j2", dest: "/home/clivern/.aliases", mode: "0600" }
      - { src: "exports.j2", dest: "/home/clivern/.exports", mode: "0600" }
      - { src: "functions.j2", dest: "/home/clivern/.functions", mode: "0600" }

  - name: append custom config loading to root bashrc
    blockinfile:
      path: "/root/.bashrc"
      block: |
        # Load custom configuration files
        if [ -f ~/.aliases ]; then
          . ~/.aliases
        fi

        if [ -f ~/.exports ]; then
          . ~/.exports
        fi

        if [ -f ~/.functions ]; then
          . ~/.functions
        fi
      marker: "# {mark} ANSIBLE MANAGED BLOCK - custom files"
      mode: "0600"

  - name: append custom config loading to clivern bashrc
    blockinfile:
      path: "/home/clivern/.bashrc"
      block: |
        # Load custom configuration files
        if [ -f ~/.aliases ]; then
          . ~/.aliases
        fi

        if [ -f ~/.exports ]; then
          . ~/.exports
        fi

        if [ -f ~/.functions ]; then
          . ~/.functions
        fi
      marker: "# {mark} ANSIBLE MANAGED BLOCK - custom files"
      owner: "clivern"
      group: "clivern"
      mode: "0600"
