# MIT License
#
# Copyright (c) 2010 Clivern
#
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in all
# copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
# SOFTWARE.

secrets:
  # $ op secret add ngrok_auth_token xxxxxxxxxxxxxxxxxxxxx -t ngrok -f
  ngrok_auth_token: ngrok_auth_token

tasks:
  - name: Download ngrok
    unarchive:
      src: https://bin.equinox.io/c/bNyj1mQVY4c/ngrok-v3-stable-darwin-arm64.zip
      dest: /tmp
      remote_src: yes
    when: ansible_os_family == "Darwin"

  - name: Copy ngrok
    copy:
      src: /tmp/ngrok
      dest: ~/bin/ngrok
      mode: a+x
      force: true
    when: ansible_os_family == "Darwin"

  - name: Download ngrok
    unarchive:
      src: https://bin.equinox.io/c/bNyj1mQVY4c/ngrok-v3-stable-linux-amd64.tgz
      dest: /tmp
      remote_src: yes
    when: ansible_os_family == "Debian"

  - name: Copy ngrok
    copy:
      src: /tmp/ngrok
      dest: /usr/local/bin/ngrok
      mode: a+x
      force: true
    when: ansible_os_family == "Debian"

  - name: Add auth token
    command: ngrok config add-authtoken {{ ngrok_auth_token }}

  - name: Get version
    command: ngrok version
    register: output

  - debug: msg="{{ output.stdout }}"
