#!/bin/bash

cd /tmp

curl -LO https://releases.hashicorp.com/packer/1.8.4/packer_1.8.4_darwin_amd64.zip
unzip packer_1.8.4_darwin_amd64.zip
rm packer_1.8.4_darwin_amd64.zip
chmod +x ./packer
mv -f packer $LOCAL_BIN/packer
