#!/bin/bash

cd /tmp

export VAULT_VERSION=1.13.3
echo "Installing Vault v$VAULT_VERSION"

curl -sS https://releases.hashicorp.com/vault/{$VAULT_VERSION}/vault_{$VAULT_VERSION}_darwin_amd64.zip > vault.zip

unzip vault.zip

chmod +x ./vault

mv -f vault $LOCAL_BIN/vault

rm vault.zip
