source 'https://rubygems.org'

gem 'jekyll', '3.9.0'
gem "kramdown-parser-gfm", "~> 1.1"
gem "webrick", "~> 1.8"

group :jekyll_plugins do
  gem 'jekyll-paginate'
  gem 'jekyll-sitemap'
  gem 'github-pages'
end
